## Simple Problem

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from fastncut import FastNcut

# all element be same value
const = np.array([[0,1],[0,2]])
A = np.array([[2, 0, 0],[0, 1, 0],[0, 0, 0]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 2th element be same value in the eigen vector.
1th element  and 3th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 4.303937336545527
 Iteration : 2 residual : 0.5438682426209729
 Iteration : 3 residual : 0.0
constrained eigen vector : 
 [[1.34164079]
 [1.34164079]
 [1.34164079]]


In [2]:
# all element be same value
const = np.array([[0,1]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 2th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 5.5045227422206615
 Iteration : 2 residual : 0.597672336063205
 Iteration : 3 residual : 0.0
constrained eigen vector : 
 [[1.34164079]
 [1.34164079]
 [0.        ]]


In [4]:
# all element be same value
const = np.array([[0,2]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 3th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 0.13748389401327876
 Iteration : 2 residual : 2.220446049250313e-16
constrained eigen vector : 
 [[0.18616554]
 [0.98251839]
 [0.18616554]]


In [5]:
np.zeros([3,1])

array([[0.],
       [0.],
       [0.]])

In [7]:
a,b = 1,2

In [8]:
a

1

In [9]:
b

2

In [10]:
a,b = [0,1]

In [11]:
a

0

In [12]:
b

1